#!/usr/bin/env bash
# This script installs and configures HAProxy on a new Ubuntu machine

# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
sudo bash -c 'cat > /etc/haproxy/haproxy.cfg <<EOF
frontend lb-frontend
    bind *:80
    mode http
    default_backend lb-backend

backend lb-backend
    mode http
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
EOF'

# Enable HAProxy service
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAProxy
sudo service haproxy restart
